### ISSUE TITLE
/api/article/view/{articleId}  API 수정 요청

### ISSUE THREAD

**Issue by jijiseong** [CASPER-REPSAC/newsper#2]
## 문제
프로필 이미지랑 소개글 필요함
파일 빈배열로 오는 문제 있음,
그리고 파일 명도 필요해서 이런 형식으로 줘

## 원하는 형식

```
{
  article: {
    // 기존 것들그대로
    profile: string 
    introduce: string
  },

  files: [ 
    {
      name: "파일 명.jpg"
      src: "http://파일경로~~"
    },
    {
      name: "파일 명2.jpg"
      src: "http://파일경로2~~"
    }
  ]
}
```

**Comment by ine9141** [comment]
-완-

**Comment by jijiseong** [comment]
```
{
  files: [
    'http://build.casper.or.kr/file/2024/05/12/3956787e-e67f-4056-8347-0cd8d20e7cbc_test.png'
  ],
  article: {
    //... 
  }
}
```

지금 이렇게 오는데

**Comment by ine9141** [comment]
{
  "files":[
    "http://build.casper.or.kr/file/2024/05/12/00dbba39-3870-43b8-a5d3-cc7164fed6d0_test2.png",
    "http://build.casper.or.kr/file/2024/05/12/857dfbc3-e3ab-4813-bc4d-07f3c19274a4_test.png"
  ],
"article":{
  "introduce": null,
  "modifiedAt": "2024-05-12T19:32:04.217+00:00",
  "profile": "http://build.casper.or.kr/profile/2024/05/12/5c63f510-82d4-43a0-bd5b-e20158188813_test.png",
  "articleId": 235,
  "title": "file_test",
  "numOfComments": 0,
  "userId": "ine",
  "content": "[{\"id\":\"7ff960c6-8376-4583-a8e7-c277998bc3b5\",\"type\":\"paragraph\",\"props\":{\"textColor\":\"default\",\"backgroundColor\":\"default\",\"textAlignment\":\"left\"},\"content\":[{\"type\":\"text\",\"text\":\".\",\"styles\":{}}],\"children\":[]},{\"id\":\"097640e8-458f-470a-bba5-5c0ca14efbaf\",\"type\":\"paragraph\",\"props\":{\"textColor\":\"default\",\"backgroundColor\":\"default\",\"textAlignment\":\"left\"},\"content\":[],\"children\":[]}]",
  "createdAt": "2024-05-12T19:32:04.217+00:00",
  "hide": false,
  "view": 6,
  "nickname": "ine",
  "boardId": "freedom_board",
  "category": "all",
  "notice": false
  }
}

이렇게 오는거 아녜여?
235번 view에여

**Comment by jijiseong** [comment]
files에 name 필요함

**Comment by ine9141** [comment]
수정 했습니당!
